version: '3.1'

services:
  postgres_db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    volumes:
      - live-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3   
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s      
  weather:
    image: 127.0.0.1:5000/weather-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      - DJANGO_SETTINGS_MODULE=weather.production      
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
                   
volumes:
  live-db-data:      
