version: '3.1'

services:
  weather:
    build: .
    image: weather-app
    ports:
      - "8000:8000"
    volumes:
      - .:/weather
    command: /weather/start_local.sh
    stdin_open: true
    tty: true
    depends_on:
      - postgres_db
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 30s
      retries: 5   
    entrypoint: /weather/wait-for-postgres.sh postgres 5432
  
  postgres_db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3   

volumes:
  db-data:
