version: '3.1'

services:
  postgres_db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    volumes:
      - live-db-data:/var/lib/postgresql/data
  weather:
    image: 127.0.0.1:5000/weather-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    deploy:
      replicas: 1
    resources:
      limits:
        cpus: '0.50'
        memory: 300M     
            
volumes:
  live-db-data:      
