version: '3.1'

services:
  weather:
    build: .
    image: weather-app
    ports:
      - "8002:8002"
    volumes:
      - .:/weather
    environment:
      - DJANGO_SETTINGS_MODULE=weather.settings
    stdin_open: true
    tty: true
    depends_on:
      - postgres_db
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
    command: "/weather/start_local.sh"
  
  postgres_db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3   

volumes:
  db-data:
