version: '3.1'

services:
  postgres_db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    volumes:
      - db-data:/var/lib/postgresql/data

  weather:
    build: .
    image: 127.0.0.1:5000/weather-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    command: /weather/start.sh
volumes:
  db-data:
