version: '3.1'

services:
  postgres_db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  weather:
    build: .
    image: weather-app
    ports:
      - "8000:8000"
    volumes:
      - .:/weather
    depends_on:
      postgres_db:
        condition: service_healthy       
    command: /weather/start_local.sh
    stdin_open: true
    tty: true      

volumes:
  db-data:
