version: '3.1'

services:
  postgres_db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    volumes:
      - db-data:/var/lib/postgresql/data

  weather:
    build: .
    image: weather-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    volumes:
      - .:/weather
    command: /weather/start_local.sh
    stdin_open: true
    tty: true

volumes:
  db-data:
