# Generated by Django 2.2.3 on 2019-07-26 11:58

from django.db import migrations, models
import weather_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_weatherinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=weather_app.models.OverwriteStorage(), upload_to='photos'),
        ),
    ]
